# 配置dev环境
server:
  port: 8084
spring:
  jpa:
    #启动时是否创建表，默认为false
    generate-ddl: true
    #是否在控制台 显示sql语句，默认为false
    show-sql: true
    hibernate:
      #设置启动时，默认不重新建表
      ddl-auto: none
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud02?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
  profiles: dev
    #指定当前微服务对象（提供者）暴露的名称
  application:
    name: vince-provider-depart


#设置日志输出格式
logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info #spring boot 启动时的日志级别
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor : trace
    com.vince.provider: debug
eureka:
  client:
    service-url: #指定注册服务中心地址
      #defaultZone: http://eureka8100.com:8100/eureka,http://eureka8200.com:8200/eureka,http://eureka8300.com:8300/eureka
      defaultZone: http://eureka8400.com:8400/eureka
      #指定当期客户端在注册中心的名称
    #instance:
    # instance-id: abc-vince-provider-depart:8081

---
# 配置test环境
server:
  port: 8085
spring:
  jpa:
    #启动时是否创建表，默认为false
    generate-ddl: true
    #是否在控制台 显示sql语句，默认为false
    show-sql: true
    hibernate:
      #设置启动时，默认不重新建表
      ddl-auto: none
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud03?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=true
    username: root
    password: root

  profiles: test
  # 指定当前微服务对象（提供者）暴露的名称
  application:
    name: vince-provider-depart


#设置日志输出格式
logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info #spring boot 启动时的日志级别
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor : trace
    com.vince.provider: debug
eureka:
  client:
    service-url: #指定注册服务中心地址
      #defaultZone: http://eureka8100.com:8100/eureka,http://eureka8200.com:8200/eureka,http://eureka8300.com:8300/eureka
      defaultZone: http://eureka8500.com:8500/eureka
      #指定当期客户端在注册中心的名称
    #instance:
    # instance-id: abc-vince-provider-depart:8081